# Generated by Django 2.2.3 on 2019-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.TextField(max_length=3)),
                ('Strain', models.TextField(max_length=200)),
                ('Genotype', models.TextField()),
                ('Contact', models.TextField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('Days', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
