# Generated by Django 2.2.6 on 2020-01-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Strain', models.TextField(choices=[('Black6', 'Black6'), ('129S1/SvImJ', '129S1/SvImJ'), ('129X1/SvJ', '129X1/SvJ'), ('A/J', 'A/J'), ('AKR/J', 'AKR/J'), ('BALB/cByJ', 'BALB/cByJ'), ('BALB/cJ', 'BALB/cJ'), ('BTBR T+ Itpr3tf/J', 'BTBR T+ Itpr3tf/J'), ('C3H/HeJ', 'C3H/HeJ'), ('C57BL/6J', 'C57BL/6J'), ('C57BL/6NJ', 'C57BL/6NJ'), ('C57BL/10J', 'C57BL/10J'), ('CBA/J', 'CBA/J'), ('CBA/CaJ', 'CBA/CaJ'), ('DBA/1J', 'DBA/1J'), ('DBA/2J', 'DBA/2J'), ('FVB/NJ', 'FVB/NJ'), ('NOD/ShiLtJ', 'NOD/ShiLtJ'), ('SJL/J', 'SJL/J'), ('TALLYHO/JngJ', 'TALLYHO/JngJ')], max_length=1)),
                ('Genotype', models.TextField()),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
