# Generated by Django 2.2.3 on 2019-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='Days',
        ),
        migrations.AlterField(
            model_name='paste',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
