# Generated by Django 2.2.6 on 2020-02-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20200214_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='Contact',
            field=models.ForeignKey(choices=[('e', 'a.email')], on_delete=django.db.models.deletion.CASCADE, to='accounts.Activation'),
        ),
    ]
