# Generated by Django 2.2.3 on 2019-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20190820_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='Strain',
            field=models.TextField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
