# Generated by Django 2.2.3 on 2019-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20190820_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='Strain',
            field=models.TextField(choices=[('Black6', 'Black6'), ('Black7', 'Black7'), ('129S1/SvImJ', '129S1/SvImJ'), ('129X1/SvJ', '129X1/SvJ'), ('A/J', 'A/J'), ('AKR/J', 'AKR/J'), ('BALB/cByJ', 'BALB/cByJ'), ('BALB/cJ', 'BALB/cJ'), ('BTBR T+ Itpr3tf/J', 'BTBR T+ Itpr3tf/J'), ('C3H/HeJ', 'C3H/HeJ'), ('C57BL/6J', 'C57BL/6J'), ('C57BL/6NJ', 'C57BL/6NJ'), ('C57BL/10J', 'C57BL/10J'), ('CBA/J', 'CBA/J'), ('CBA/CaJ', 'CBA/CaJ'), ('DBA/1J', 'DBA/1J'), ('DBA/2J', 'DBA/2J'), ('FVB/NJ', 'FVB/NJ'), ('NOD/ShiLtJ', 'NOD/ShiLtJ'), ('SJL/J', 'SJL/J'), ('TALLYHO/JngJ', 'TALLYHO/JngJ')], max_length=1),
        ),
    ]
