# Generated by Django 2.2.6 on 2020-03-02 00:30

from django.db import migrations
import jsonfield.fields
import pastebin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20200214_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='Contact',
            field=jsonfield.fields.JSONField(blank=True, default=pastebin.models.Paste.contact_default, verbose_name='ContactInfo'),
        ),
    ]
