# Generated by Django 2.2.6 on 2019-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
